services:
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=sahabatqurandb'
      - 'POSTGRES_PASSWORD=sahabatquran1234'
      - 'POSTGRES_USER=sahabatquran'
    ports:
      - '54321:5432'
    volumes:
      - ./db-sahabatquran:/var/lib/postgresql/dat
